name: TimeLimitCMD
main: iJoshuaHD\Main
version: 0.0.1
api: [1.6.0]
load: STARTUP
author: iJoshuaHD
description: Limit Command Execution Interval
website: https://github.com/ijoshuahd/TimeLimitCMD
commands:
 tlcmd:
  description: "Time Limit CMD Manager"
  permissions: tl.command.cmd
permissions:
 tl:
   description: "Parent permission for TimeLimitCMD"
   children:
    tl.command:
     description: "Allows using TimeLimitCMD commands"
     children:
      tl.command.cmd:
       description: "Allow using /tlcmd"
       default: op
